name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Baixa o Theos de forma ultra rápida
          git clone --depth 1 --recursive https://github.com/theos/theos.git $HOME/theos
          
          # Baixa os SDKs direto (método Git para não dar erro de unzip)
          git clone --depth 1 https://github.com/theos/sdks.git $HOME/theos/sdks
          
          # Configura as variáveis para o sistema encontrar o Theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "$HOME/theos/bin" >> $GITHUB_PATH

      - name: Build Tweak
        run: |
          # Comando para compilar
          export THEOS=$HOME/theos
          make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MeuModFinal
          path: packages/*.deb
