name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Instala as ferramentas de sistema
          brew install ldid dpkg xz
          
          # Baixa o Theos de forma limpa
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          
          # Configura o SDK
          mkdir -p $HOME/theos/sdks
          ln -s /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk $HOME/theos/sdks/iPhoneOS14.5.sdk
          
          # CONFIGURAÇÃO DE AMBIENTE
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "$HOME/theos/bin" >> $GITHUB_PATH

      - name: Build Tweak
        run: |
          export THEOS=$HOME/theos
          
          # Força o Theos a usar o dpkg-deb do sistema, ignorando o dm.pl quebrado
          make clean
          make package FINALPACKAGE=1 THEOS_DEVICE_IP=localhost THEOS_PACKAGE_SCHEME=rootless
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MeuModFinal
          path: packages/*.deb
