name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Theos
        run: |
          sudo git clone --recursive https://github.com/theos/theos.git /opt/theos
          sudo git clone https://github.com/theos/sdks.git /opt/theos/sdks
          echo "THEOS=/opt/theos" >> $GITHUB_ENV

      - name: Build Tweak
        run: |
          export THEOS=/opt/theos
          make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MeuModFinal
          path: packages/*.deb
