name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # Baixa o Theos de forma leve
          git clone --depth 1 --recursive https://github.com/theos/theos.git $HOME/theos
          
          # Baixa o SDK de um repositório que já vem extraído (evita o Erro 9 do unzip)
          git clone --depth 1 https://github.com/theos/sdks.git $HOME/theos/sdks
          
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "$HOME/theos/bin" >> $GITHUB_PATH

      - name: Build Tweak
        run: |
          # Compila o arquivo final
          make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MeuModFinal
          path: packages/*.deb
